name: Docker Image CI
on: 
    push:
      branches:
        - master
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag nun-db-prometheus-exporter:latest
    - name: Re-tag
      run: docker tag nun-db:latest mateusfreira/nun-db-prometheus-exporter:latest
    - name: Publish
      run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}&&docker push mateusfreira/nun-db:latest

